### ISSUE TITLE
multiple stitch assignment

### ISSUE THREAD

**Issue by MAETempels** [d-bl/GroundForge#100]
It would be very nice if serveral ID's can be assigned to one specified stitch in one assignment. Something like `A1=B4=F2=ctcrrctcll`. 
Besides saving some typing, it will easier to specify legs one spiders.

**Comment by jo-pol** [comment]
See also issue #49, still under construction: some test cases in [StitchesSpec](https://github.com/d-bl/GroundForge/blob/assign-stitches/src/test/scala/dibl/StitchesSpec.scala#L20)

**Comment by jo-pol** [comment]
The merged branch only implements the request for the first, pair of diagrams. The level two en three pairs of diagrams are still waiting for an implementation.
