### ISSUE TITLE
mistaken ID's

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#108]
See this [help-page] and the remarks at [top left], the latter page might be subject to change. Not sure the issue holds any longer.

[help-page]: https://github.com/d-bl/GroundForge/blob/ad9a67fa3531e8493469bffd2af2496672a0c04f/docs/help/Reversed-engineering-of-patterns.md#droste-method
[top left]: https://jo-pol.github.io/GroundForge/help/Choose-Stitches#an-example

**Comment by jo-pol** [comment]
From https://github.com/d-bl/GroundForge/pull/106#issuecomment-344045450 by @MAETempels 

The matrix `5---, -C-B, 5-5-, -5-5, --5-, -B-C, 5-5-, -5-5` (no shift alias checker) doesn't work at all on the main page when following the go button. Unless you undo the footside shift, but changing the footside shift always invalidates ID's and as such is not part this issue.

The following pattern is OK:
![id-problem](https://user-images.githubusercontent.com/10553630/32824311-bb5b817e-c9e0-11e7-8955-809bdcd7ea1c.png)


  | a | b | c | d
-- | -- | -- | -- | --
1 | ttctc |   | ctct |  
2 |   | ttctctc |   |  
3 | ctc |   | ctct |  
4 |   | ctctc |   | ctct

**Comment by MAETempels** [comment]
5---, -C-B, 5-5-, -5-5, --5-, -B-C, 5-5-, -5-5
works fine on main page :-) 
It was meant as example for mistaken ID's that were mentioned on #106.

**Comment by jo-pol** [comment]
The first message of this issue is about the topic of this issue. The first help page listed there is about this [triangular pattern](https://d-bl.github.io/GroundForge?m=5-%2C-5%2C5-%3Bbricks%3B16%3B10%3B0%3B2&s1=A1%3Dct%20B2%3Dcr%20B3%3Dcrcl&s2=cross%3Dctc%20twist%3Dctc&s3=) it is not possible to create the pattern with the new form of #106 because the stitch-ID's are assigned as shown in the matrix below. B3 should have been A3 for the new form to work.

  |  
-- | --
a1 |  
  | b2
b3 |  

I wonder if the problem is limited to matrices with an odd number of rows and/or columns, and if all odd rows of such matrices are affected, or just the last.

**Comment by jo-pol** [comment]
Closing this issue. 

An experimental convenience form in branch [brick-variations](https://github.com/d-bl/GroundForge/tree/brick-variations) will lead to another approach, likely making the current pattern links deprecated.

This new approach replaces the brick/checker options with two shift parameters allowing more types of translations. To play with the new form, download or checkout the branch and try `docs/_includes/tiles-form.html` in your browser. There will only be a 'go' button at the bottom of the page for the old checker/brick patterns where the bricks are shifted by half a brick.
