### ISSUE TITLE
Minimal matrices

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#111]
According to @veronika all patterns can be defined with a checker matrix. But as @MAETempels experienced it can be quite elaborate to define stitches for a matrix with much  redundancy.

An experimental convenience form in the branch [brick-variations](https://github.com/d-bl/GroundForge/tree/brick-variations) replaces the (half-)brick / checker options with two shift parameters allowing bricks with another shift and vertical bricks. To play with the new form, download or checkout the branch and try `docs/_includes/tiles-form.html` in your browser. There will only be a 'go' button at the bottom (targeting the main page with pair and thread diagrams) of the page for checker patterns or when the bricks are shifted horizontally by half a brick.

The figures below show two situations with even wilder repeat methods: gaps and overlap. The left example has diagonals of overlapping tiles, but the diagonals snugly fit together. For the (faint) Flanders/Rose ground on the right, matrices that overlap in both directions and also have gaps seem to reflect a traditional/natural understanding of the repeats. The overlapping parts even have a Dutch name: afkruisingen. So I guess I could use shift parameters for the south-east and south-west direction. Stitch assignments are only needed for the non overlapping parts.

Any more thoughts? Am I missing something that might be useful without over-complicating the subject? Applying wall-paper reflections are clearly too complicated: it has a high risk of threads looping into itself and would require different matrix encoding and assigned stitches in each segment to preserve symmetry.

![tiling](https://user-images.githubusercontent.com/10553630/34122209-f3852e6e-e42b-11e7-9eb7-cec030e3da11.png)

**Comment by jo-pol** [comment]
I implemented the prototype on the form under development. The day is too short to fix the following logic:

https://github.com/d-bl/GroundForge/blob/04834768225bdb702e3162ffffbefe936ca8b458/docs/js/tiles.js#L44-L50


To explain SW/SE (south-west / south-east):
![](https://raw.githubusercontent.com/jo-pol/GroundForge/04834768225bdb702e3162ffffbefe936ca8b458/docs/help/images/shift-directions.png)

**Comment by jo-pol** [comment]
Fixed the problem above (the go button) just mixed up east and west.

**Comment by jo-pol** [comment]
The user interface for the new form should be complete, including pop-ups from the prototype diagram to choose stitches and applying the color code. 

To feed patterns with the new tiling to the animated D3js diagram will require quite some more water to go under the bridge. The old algorithm projects an arbitrary cell to the first tile by applying a modulo to the coordinates after a correction for bricks. The new form works the other way around: it repeats tiles as far as they fit in the desired patch. The two methods don't marry very well so it might require a lot of rewriting.

**Comment by jo-pol** [comment]
The interface is still not as complete as I thought when writing the previous message in this discussion.

When implementing the new types of tiling, we might as well implement custom footsides as suggested with comments on https://github.com/MAETempels/MAE-gf/pull/11

The form then could become something as shown below. Note that the prototype does not exactly match the definition in this hacked screenshot. In the `repeats` section we may also need a line for rows and cols to show in the prototype. These lines might not belong in the repeats section, but where else? The total size of the prototype however is fixed but could be increased a little. Note that the thread diagram replaces the cheat cheat (to construct a matrix) that appears when the page is freshly loaded.

It is becoming too large and scary to become part of of the main page. Whenever everything under the hood will be working together, the parameters section might disappear from the main page.

![config-foot-sides](https://user-images.githubusercontent.com/10553630/34468933-ce4b983e-ef13-11e7-8a98-ea99d83f0fb9.png)

**Comment by MAETempels** [comment]
Nice work!

Suggestion: allow only repeats of the complete matrix in the middle instead of arbitrary numbers of collumns. The footside on the right will be the given (or the default) footside.
The prototype might do with 3 repeats horizontally, and 3 vertically (as in the pictures in the repeat-section).

There might be some difficulties with footsides with brick-matrices.

With the overlapping tiles: there are more shifts possible. Like in the example (picture): -4,0. I will try this.

**Comment by jo-pol** [comment]
With -4,0 you are missing the top row of diagonal arrows.

With bricks and overlapping matrices the meaning of complete matrix might be ambiguous. So I'd rather not use that concept.

**Comment by MAETempels** [comment]
Aha, I'm not supposed to go left of the 0-collumn.

As mentoined in pr-11 (mae-gf): the whole length of the minimal checkers matrix needs to be specified for footsides.
If the right footside-matrix is specified fitting with the main matrix, then there might be numbers of collumns where the specified right side does not fit.
Example: take the rose ground. This is a 4x4 checker matrix (without overlaps). If someone specifies 5 collumns, and a rightfootside fitting with the matrix, then this does not seem to fit. 

ps In the picture given 2 day's ago in this issue: is the leftfootside definition correct with the prototype? I seem to miss a "7": A8, -7

**Comment by jo-pol** [comment]
About the ps: A note above the hacked screenshot explains it is not consistent.

With the current version you can now design patterns with custom footsides and minimal tiles by hacking this [link]. You can find the meaning of the arguments [here]. Selected stitches are not yet applied in repeats, but you can get thread diagrams with mainly cloth stitches.

[link]: https://github.com/jo-pol/GroundForge/blob/d442e9640b67e4b093ae19c881eacd480ec6b8da/docs/_includes/tiles-form.html#L110

[here]: https://github.com/jo-pol/GroundForge/blob/d442e9640b67e4b093ae19c881eacd480ec6b8da/docs/js/tiles.js#L189

**Comment by jo-pol** [comment]
Sorry, celebrating too early, the link mentioned and hour ago currently only does checker tiles.

**Comment by jo-pol** [comment]
When [download]ing the brick-variations branch with the just published commit, you can play with the new tiling when you change the head/foot-side matrices, in these cases the thread diagram will only apply cloth stitches even if you selected  other stitches for the color-coded prototype. It's all still work in progress. 

[download]: https://github.com/d-bl/GroundForge/archive/brick-variations.zip

**Comment by jo-pol** [comment]
The page with the new form has moved to `docs/tiles.html` in the most recent download. The demo section might move to a help page when publishing the page, for now it is convenient for manual testing and keep track of the test result. Comparing the non-animated pair diagram with the prototype is convenient to check whether the stitches are applied correctly, sadly sometimes not, han't yet figured out why not.

**Comment by jo-pol** [comment]
Note on the patch size: The number of rows should equal a multitude of the height of a checker matrix.

**Comment by jo-pol** [comment]
Though it might look like minor but essential bugs, most of the work still has to be done. Nevertheless the new page is available at https://d-bl.github.io/GroundForge/tiles.html No links to it yet other than this one and no help page either.

**Comment by jo-pol** [comment]
To be comopleted with #115
