### ISSUE TITLE
level 2: ID 1a1

### ISSUE THREAD

**Issue by MAETempels** [d-bl/GroundForge#112]
When specifing a level 2 matrix, an ID 1a1 shows up. However, it is not possible to assign a stitch-value.

https://d-bl.github.io/GroundForge/index.html?m=5-5-%20%20-5-5%3Bbricks%3B7%3B5%3B0%3B0&s1=ctc%20A1%3Dtctctct&s2=ctct%20a10%3Da11%3Dc%20a19%3Dct%20a1a%3Dct%20a12%3Dctct%20a18%3Dtctc%20a15%3Da16%3Da17%3Dc%20a13%3Dcl%20a14%3Dcr&s3=

![image](https://user-images.githubusercontent.com/28353067/35048345-08f77e18-fb9d-11e7-865f-f2aaba1b048f.png)

**Comment by MAETempels** [comment]
I seem not have the rights to assign labels.

**Comment by jo-pol** [comment]
#100 was only implemented for level 1

**Comment by MAETempels** [comment]
The issue is not about multiple assignment. That worked nicely on level  2.

Please take a look at the following, level 2

https://d-bl.github.io/GroundForge/index.html?m=5-5-%20%20-5-5%3Bbricks%3B7%3B5%3B0%3B0&s1=ctc%20A1%3Dtctctct&s2=ctct%20a1a%3Dct%20a10%3Da11%3Da19%3Da12%3Da18%3Da15%3Da16%3Da17%3Da13%3Da14%3Dctc&s3=

All stitches get nicely assigned, EXCEPT a1a ...

Even if just specified  a1a=ct , then all get ctc.

**Comment by jo-pol** [comment]
fixed with bd1f8ca
