### ISSUE TITLE
checker matrices / first steps of the footside trick

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#123]
Context: https://d-bl.github.io/GroundForge/help/Tiles#foot-side-trick
* figure out the dimensions of a checker matrix
* fill out (perhaps at most 5 columns?) in the side panels of the matrices
* set the recommended default stitches

A tool tip should warn assigned stitches get lost

**Comment by jo-pol** [comment]
About the first bullet: the size of a checker matrix.
==============================
![](https://raw.githubusercontent.com/jo-pol/GroundForge/4bfc457506b97851b76411fe229e511076495996/docs/help/images/shift-directions.png)

It boils down to tiles returning to the row or column of the first tile after a few sort of "knight moves", to stay with the terminology of the checker game. So the size of the tile does not matter. After the least common multiple of horizontal moves, a tile arrives at the same column. After the least common multiple of vertical moves, a tile arrives at the same tiles. 

The math libraries don't seem to have such functions: [javascript](https://www.w3schools.com/js/js_math.asp), [scala-js](https://www.scala-js.org/api/scalajs-library/0.5.2/index.html#scala.scalajs.js.Math$). It needs prime numbers. As we are not dealing with large numbers, say 20 or 30 at most, a 2D table with the solutions could provide a simple implementation. Whenever larger numbers are provided, the button should do nothing. After all it is just a convenience function.

**Comment by jo-pol** [comment]
A diagram by @MAETempels with annotations that illustrate the basis my own reasoning

![afbeelding](https://user-images.githubusercontent.com/10553630/48799308-0d63d300-ed07-11e8-88ba-7fd648c3a24f.png)
The arrowheads illustrate the form values, purple is (3,3), green is (-4,2). Note that (0,0) sits in the top left as usual for canvases. The light blue checker is 18*18. Te other blue lines illustrate the moves needed to get the tile in the same row/column. Both types of tiles require the same set of moves.

**Comment by jo-pol** [comment]
Thanks for the elaborate explanation and very helpful procedure. Good work.

Some additional remarks: At first sight, the starting point would be the purple and green vectors of the form. Valid vectors according to the form are east-to-south for purple and south to west for green. The opposite of the green vector would establish in the width.

The solid tiles as shown in the image below can initialize the vectors.

![afbeelding](https://user-images.githubusercontent.com/10553630/48850394-de05a280-eda8-11e8-980a-b31ecdeffa55.png)
As the open tiles more or less show, a checker tiling is initialized as purple-SE and green-W. But other configurations can generate valid diagrams too, like purple-E/green-south or purple-S/green-E. The latter two would be a problem if not checked as an exception in advance: you would only walk in some SE direction. In fact the lengths of these vectors are the dimensions of the checker tile.

**Comment by MAETempels** [comment]
I think, the starting vector would indeed be the purple, but not the green, but (purple minus green). 

I think there is a general rule about which ones to choose. Something like not being the sum of the others (see the 8 possible vectors). In a checker-tiling, the purple diagonal vector is the sum of the horizontal and vertical vector. As can be seen in the picture in my contribution on this issue yesterday.

**Comment by jo-pol** [comment]
Obsolete subject since instructions to create foot sides are simplified from 
https://github.com/d-bl/GroundForge/blob/0233952/docs/help/Tiles.md#foot-side-trick
to
https://github.com/d-bl/GroundForge/blob/69d234f/docs/help/Tiles.md#foot-sides
