### ISSUE TITLE
the patch part of prototype diagrams sometimes has missing tiles

### ISSUE THREAD

**Issue by MAETempels** [d-bl/GroundForge#133]
The following matrix shows a hole at the bottom:
[hole](https://d-bl.github.io/GroundForge/tiles?patchWidth=3&patchHeight=8&g1=ctc&f1=ctc&c1=ctc&b1=rctcl&f2=ctc&c2=ctcl&b2=ctcr&a2=ctctl&footside=x1,48&tile=1,8&headside=17,8x&footsideStitch=ctc&tileStitch=ctc&headsideStitch=ctc&shiftColsSW=0&shiftRowsSW=2&shiftColsSE=1&shiftRowsSE=2)

Setting the patchWidth higher solves the hole (but makes one at the side).
Setting the shiftparameters different solves the problem, althougd the specified matrix is a "purple" one.    

[different shifts](https://d-bl.github.io/GroundForge/tiles?patchWidth=3&patchHeight=8&g1=ctc&f1=ctc&c1=ctc&b1=rctcl&f2=ctc&c2=ctcl&b2=ctcr&a2=ctctl&footside=x1,48&tile=1,8&headside=17,8x&footsideStitch=ctc&tileStitch=ctc&headsideStitch=ctc&shiftColsSW=-1&shiftRowsSW=2&shiftColsSE=0&shiftRowsSE=2)

**Comment by jo-pol** [comment]
https://github.com/d-bl/GroundForge/blob/8505b07b35f255c89e0cbd32a3fc7d947a5e1192/src/main/scala/dibl/proto/TilesConfig.scala#L111-L132

Doesn't always repeat the the input matrix properly until it fills the dimensions specified for the patch.

**Comment by MAETempels** [comment]
Maybe the code needs to go beyond TotalRows (if (rt >= 0 && ct >= 0 && rt < totalRows && ct < centerCols) )
Rt < totalRows + lenght(matrix) ??

In my previous example is "pair 1" floating on the bottom of the pairs diagram. In Jo's alternative its seems missing completely.

As already mentioned: it seems to depend on the choice of the green and purple vectors. If they are chosen "well", the diagram fills nicely.  Chosen well: the green and purple vector can generate all upper left corners of the matrix by just adding and substracting.

More examples:

https://d-bl.github.io/GroundForge/tiles?patchWidth=3&patchHeight=10&a1=ctc&a2=ctc&tile=1,8&footsideStitch=ctc&tileStitch=ctc&headsideStitch=ctc&shiftColsSW=0&shiftRowsSW=2&shiftColsSE=1&shiftRowsSE=0

https://d-bl.github.io/GroundForge/tiles?patchWidth=9&patchHeight=9&b1=ctct&a1=ctct&c2=ctct&a2=ctct&c3=ctct&b3=ctct&tile=14-,8-2,-58&footsideStitch=ctctt&tileStitch=ctct&headsideStitch=ctctt&shiftColsSW=1&shiftRowsSW=3&shiftColsSE=3&shiftRowsSE=1

https://d-bl.github.io/GroundForge/tiles?patchWidth=4&patchHeight=17&h1=ctc&g1=ctctt&c1=ctc&b1=rctcl&g2=ctc&c2=ctcl&b2=ctcr&a2=ctctt&footside=x1,48&tile=1,8&headside=17,8x&footsideStitch=ctc&tileStitch=ctc&headsideStitch=ctc&shiftColsSW=0&shiftRowsSW=2&shiftColsSE=1&shiftRowsSE=2

The following one works as expected, but the green and purple vector seem to have changed roles:
https://d-bl.github.io/GroundForge/tiles?patchWidth=3&patchHeight=19&g1=ctc&f1=ctc&c1=ctc&b1=rctcl&f2=ctc&c2=ctcl&b2=ctcr&a2=ctctt&footside=x1,48&tile=1,8&headside=17,8x&footsideStitch=ctc&tileStitch=ctc&headsideStitch=ctc&shiftColsSW=1&shiftRowsSW=0&shiftColsSE=0&shiftRowsSE=2

**Comment by MAETempels** [comment]
Some thought:

Suppose, we have a matrix A of size r rows and c columns. For the sake of the argument, we can set this size to 1x1.

This matrix sits in the raster as follows:
GHI
FAB
EDC

If we take the green and purple parameters as g=(0,1) and p=(1,1) and we apply a*g o b*p where a,b in {-1,0,1}  we get the following:
-GH-
KFAB
--DCL
Positions I and E are not reached.

Taking g=(1,0) p=(0,1) gives all neighbours.
For some reason g=(0,1), p=(1,0) draws a square size smallest(patch-row,patch-col).

See the examples a-e below.

However, see the overlapping matrix:
https://d-bl.github.io/GroundForge/tiles?patchWidth=12&patchHeight=12&c1=ct&b1=ct&a1=ct&c2=ct&a2=ct&c3=ct&b3=ct&a3=ct&tile=831,4-7,158,&footsideStitch=ctctt&tileStitch=ct&headsideStitch=ctctt&shiftColsSW=0&shiftRowsSW=4&shiftColsSE=4&shiftRowsSE=0
Choose diagonal vectors:
https://d-bl.github.io/GroundForge/tiles?patchWidth=12&patchHeight=12&c1=ct&b1=ct&a1=ct&c2=ct&a2=ct&b3=ct&tile=831,4-7,158,&footsideStitch=ctctt&tileStitch=ct&headsideStitch=ctctt&shiftColsSW=-2&shiftRowsSW=2&shiftColsSE=2&shiftRowsSE=2
Whereas:
https://d-bl.github.io/GroundForge/tiles?patchWidth=15&patchHeight=15&b1=ct&a1=ct&c2=ct&a2=ct&b3=ct&a3=ct&tile=831,4-7,158,&footsideStitch=ctctt&tileStitch=ct&headsideStitch=ctctt&shiftColsSW=2&shiftRowsSW=2&shiftColsSE=4&shiftRowsSE=0
is incomplete
(0,4),(2,2) seems complete (but not as shiftcols = 25)



(a) (0,1)(1,1)
https://d-bl.github.io/GroundForge/tiles?patchWidth=5&patchHeight=11&a1=ctct&tile=1&footsideStitch=ctctt&tileStitch=ctct&headsideStitch=ctctt&shiftColsSW=0&shiftRowsSW=1&shiftColsSE=1&shiftRowsSE=1
(gives an empty corner, adding columns makes the empty's go away)
(b) (1,0)(0,1)
https://d-bl.github.io/GroundForge/tiles?patchWidth=11&patchHeight=16&a1=ctct&tile=1&footsideStitch=ctctt&tileStitch=ctct&headsideStitch=ctctt&shiftColsSW=1&shiftRowsSW=0&shiftColsSE=0&shiftRowsSE=1
(seems complete)
(c) (0,1)(1,0)
https://d-bl.github.io/GroundForge/tiles?patchWidth=6&patchHeight=11&a1=ctct&tile=1&footsideStitch=ctctt&tileStitch=ctct&headsideStitch=ctctt&shiftColsSW=0&shiftRowsSW=1&shiftColsSE=1&shiftRowsSE=0
(gives empty rows)
(d) (0,1)(1,0)
https://d-bl.github.io/GroundForge/tiles?patchWidth=12&patchHeight=8&a1=ctct&tile=1&footsideStitch=ctctt&tileStitch=ctct&headsideStitch=ctctt&shiftColsSW=0&shiftRowsSW=1&shiftColsSE=1&shiftRowsSE=0
(gives empty colums)
(e) (-1,0)(0,1)
https://d-bl.github.io/GroundForge/tiles?patchWidth=8&patchHeight=16&a1=ctct&tile=1&footsideStitch=ctctt&tileStitch=ctct&headsideStitch=ctctt&shiftColsSW=-1&shiftRowsSW=0&shiftColsSE=0&shiftRowsSE=1
(seems correct)

**Comment by MAETempels** [comment]
- continued from yesterday -

_If we take the green and purple parameters as g=(0,1) and p=(1,1) and we apply ag o bp where a,b in {-1,0,1} we get the following:
...
Positions I and E are not reached._
Applying the parameters again filles I and E, but leaves open other positions in the corners.

If someone specifies vectors e.g. (2,0) and (1,1) we can not know if there is also a vector like (0,2) which can generate the field. For knowing that we have to know beforehand the pattern required. (Have no example.) 

==> The **solution** to the problem "missing tiles" might be increasing the number of steps performed to generate the prototype, and display rows and collumns as specified by the patch-size.

**Comment by MAETempels** [comment]
- continued

Maybe the issue exists because of too less movement "up" and/or "left" by the given vectors.
In all "incomplete" examples above, the numbers in the shiftparameters are >= 0 !
Vectorwise, this should not make a difference. Even more, the green and purple vectors should be interchangable, as it does not matter whether I apply first the green one or first the purple one.

I wondered how I would proceed to fill the complete prototype, given the Matrix and vectors.
See attachtment. (Not exhaustedly tested)
[tiles.pdf](https://github.com/d-bl/GroundForge/files/3365679/tiles.pdf)

**Comment by jo-pol** [comment]
Don't yet tried to follow all the reasoning above. But you triggered wild thoughts about a completely new recursive approach. Sometimes it is better to start all over again than try to fix.

Lets start with a simple checker pattern.

```
ADIP
CBGN
HFEL
OMKJ
```

The first repeat A sits in the top left corner. Lets assume [Pc,Pr] and [Gc,Gr] (Green/Purple, row/col) has no positive value for Gc and no negative values for the other values. The input fields warn with read colours when these assumptions are violated.

A repeated with P produces B, B repeated with G produces C, B repeated with [-Gc,-Gr] produces D. Let us try to find the conditions to apply this procedure recursively to B-C-D. We need to apply all three step to B to produce E,F,G; C needs only to to apply the second step to produce H and I only needs to apply the last step. 

Summarized we get:
A->BCD; B->EFG, C->H, G->I; E->JKL, F->M, G->N, H->O, I->P; and so on.

For horizontal bricks C and O would be copied partly outside the target matrix. Perhaps a modulo can move that part to the far right. Similar for M and O for vertical bricks.

So far for simple cases. Another time I will continue to think about more complex cases with overlapping tiles and/or gaps between tiles.

**Comment by MAETempels** [comment]
Why the restrictions? 
As we apply P AND -P, then no restriction is needed. Maybe the performance will be slighty better if it is required that at least 2 of Pc,Pr,Gc,Gr are >= 0.

If Pc =0  or Pr = 0, then A->C resp A->D.
Even so: B->D only if Gr=0. 
Unless the given matrix has to be understood as "not in line".

(A recursive method is given in the attatchment of my previous entry.)

**Comment by jo-pol** [comment]
I just wanted to start simple with the assumptions but forgot I implicitly applied another assumption. It doesn't cater for P(urple) moving horizontally and G(reen) vertically. My procedure above would only work when using the predefined buttons for checker and bricks. P is internally called south-west and G south-east. That naming convention, originating from the checker button implementation gave birth to the assumptions.

I overlooked your attachment. What do you mean with `ip x 0 x pc`? Multiplication by zero always gives zero! I only see iteration, no recursion (a function calling itself).

My thoughts on recursion was about collections of tiles. The first collection is a single tile: the original source matrix sitting in the top left corner of the target matrix. It produces its neighbours (as far as partly in the target matrix) by applying P and G resulting in a new collection. Then apply the same algorithm to the new collection. Tiles in a north-west direction will be in previous collections and should be skipped, but that condition becomes a bit vague.

I could write a test program that visualizes the result with a drawing boxes. A different color for each recursion step. Applying semitransparent boxes will reveal duplicates by darker colors.

**Comment by MAETempels** [comment]
Confused recursive and iterative. 
(You applied Green as being "south":  G(B) = D ...)

ip x 0 x pc:  
To get to the 8 direct neighbours of the tile, I aplied every combination of g, p o g, -p o g, etc. To check on completeness, I included the 0's. See the comment after //. Of course, in actual code I would not write them.

The algorithme in my attatchment can easily be adapted to act on tiles:
As follows:

Until completely filled target matrix:
    Produce all neighbours of tile by applying all 8 pog, -pog, etc.
next tile 
(Still iterative!)

You have to keep track off the image positions of (0,0), and of their images ... Even if they are NOT in the target matrix, since their next neighbours might (partially) be.
(Maybe this is why the current algorithme has a hickup ..)
And keep track of "tiles already done".

**Comment by jo-pol** [comment]
I edited my previous message online with an image you will be familiar with.

It is funny to see that brick tiles only seem to have six neighbours. In the overlapping case even four would be sufficient. That might be clue to avoid duplicates. I don't think I need to keep track of neighbours outside the target matrix, as these would produce duplicates of tiles neighbouring those inside.

**Comment by MAETempels** [comment]
Bricks: I think there are 8
Marix( (0,0), (1,0)). Vector (-2,0) and (1,1)
Gives neigbours
(3,1) (1,1) (-1,1) (2,0) (-2,0) (1,-1) (-1,-1) (-3,-1)

Not sure about the tiles outside target matrix.  Have to draw pictures.

**Comment by MAETempels** [comment]
Bricks: I think there are 8
Marix( (0,0), (1,0)). Vector (-2,0) and (1,1)
Gives neigbours
(3,1) (1,1) (-1,1) (2,0) (-2,0) (1,-1) (-1,-1) (-3,-1)

Not sure about the tiles outside target matrix.  Have to draw pictures.

**Comment by jo-pol** [comment]
It seems each iteration needs to produce at most four neighbours per tile:
![afbeelding](https://user-images.githubusercontent.com/10553630/62424599-24015d00-b6d1-11e9-86b2-8f389f80ca3b.png)
Red produces blue, blue produces green and green produces red. It looks like at least one of these four (the light blue ones) are out of the target matrix or duplicates of earlier tiles. But we should also try the failing patterns.

**Comment by MAETempels** [comment]
Agreed, since (g o p)(x)=g(p(x)))
Also: (-p o p)(x) = x and (p o g)(x) = ( g o p)(x)
So: only apply  p, g, -p, -g, which gives duplicates. 

Suppose: y : = g(x) is outside the target, and a := p(y) is back in, then g(p(x))=a is indeed inside
the target matrix, provided that p(x) is in.

**Comment by MAETempels** [comment]
I think it is all about well defined vector-parameters. See the rough pictures in included file.
[neighbours.pdf](https://github.com/d-bl/GroundForge/files/3476570/neighbours.pdf)

ps: the default for horizontal bricks in groundforge is: g=(-1,1), p=(1,1)
for vertical bricks: g=(0,2), p=(1,1): leading to holes for larger numbers of rows.
I think the green one should be g=(1,-1)!  Which will cover (0,2) as gop (g after p)

ps : in Groundforge it matters which vector is "green" and which is "purple", Some specifications work better if the values for green and purple are switched.

**Comment by MAETempels** [comment]
Alas, my theory does not hold.
[alas]( https://d-bl.github.io/GroundForge/tiles?patchWidth=4&patchHeight=13&a1=ctct&a2=ctct&tile=1,1&footsideStitch=ctctt&tileStitch=ctct&headsideStitch=ctctt&shiftColsSW=1&shiftRowsSW=-1&shiftColsSE=1&shiftRowsSE=1)

This partically matrix gives all kinds of effects, I will make a table with the results.

**Comment by jo-pol** [comment]
fixed with #135
