### ISSUE TITLE
Wrong default vertical brick

### ISSUE THREAD

**Issue by MAETempels** [d-bl/GroundForge#136]
Matrix 1x2
The default for horizontal bricks in groundforge is: g=(-1,1), p=(1,1) 
![image](https://user-images.githubusercontent.com/28353067/62774654-b1fc8f80-baa5-11e9-871c-5eed659942d6.png)

Matrix 2x1
For vertical bricks: g=(0,2), p=(1,1): leading to holes for larger numbers of rows.
![image](https://user-images.githubusercontent.com/28353067/62774735-f851ee80-baa5-11e9-90f8-5fbc4e64bc09.png)
(Which leads to an empty corner sw as patchsize = 10 cols, 23 rows)

I think the green one should be g=(1,-1)! Which will cover (0,2) as gop (g after p)
![image](https://user-images.githubusercontent.com/28353067/62774841-5252b400-baa6-11e9-8376-6a573c06eafd.png)
(Leads to an empty corner sw for patchsize = 10 cols, 25 rows, allas)

**Comment by jo-pol** [comment]
I guess these are fixed on https://jo-pol.github.io/GroundForge/tiles 
Not with different defaults, but with the new algorithm of #135

**Comment by jo-pol** [comment]
fixed with #135
