### ISSUE TITLE
Layout of advanced forms

### ISSUE THREAD

**Issue by Cowboynoon** [d-bl/GroundForge#161]
I like using large patches in order to see the patterns better, but that often means that the thread diagram bumps down to a new row, making it difficult to define or arrange a repeat and see the result of the toggle/input in the prototype at the same time. As is, I currently make a change, then have to scroll up to see how it influenced the prototype and that is cumbersome.

(simply changing the screen resolution helps, but then the toggles become too small activate with the mouse/trackbpad)

May I suggest moving the define and arrange repeat forms and toggles to the far right of the screen, and bump the pair diagram (Which I hardly ever need/ have a use for) down to the next row in the layout? like this perhaps?

Layout row 1: Prototype, Thread diagram, (cheat sheet, define & arrange repeat - stacked on top of each other)
Layout row 2: Pair diagram
Layout row 3: Droste effect

The "forms for advanced users" are rather intimidating anyway, so I don't think having them far-right in an enclosed box would be much different than the current layout. 

Giving them a completely separate background colour within their enclosed boxes,  like a neutral tone, might aid their reading as "optional". Come to think of it, changing the backgrounds of all the input areas might not be a bad idea too to encourage interactivity -  a tidy visual difference between "canvasses/screens" and "forms"/"toggles".

(as an aside I once opened GF in dark mode on my mobile browser by accident, and it looked fantastic! ;)

Pierre

**Comment by jo-pol** [comment]
Another option might be to make the space for the prototype adjustable like for the other two diagrams. As of 30 rows it adds white space anyway and doesn't show the extra rows. Besides, by typing you can enter more than 30 rows/columns and ignore eventual (depending on the type of browser) red borders. The limit is merely a protection for accidental large values that could choke (slow) systems.

Not sure what you mean by stacking, I more or less understand (or are inspired) to have the advanced form as a column besides all the diagrams. I know there are a lot of fluid techniques with different layouts depending on the width of the monitor, but I'm comfortable with only a little of them. When you make the available space very narrow even the cheat sheet bumps to the next row. That may give you an impression about the width required for that column.

With all the operating systems and browser variations I didn't think to look at dark mode. That may making the choice of background colors more complex.

**Comment by Cowboynoon** [comment]
Yes, by stacking I mean exactly what you mean: the advanced forms as a column besides all the diagrams. I think that'll be awesome. The cheat sheet alone's current width is narrow enough I think and can perhaps be used as a gauge to resize the define and arrange areas?

**Comment by jo-pol** [comment]
The view port for the prototype is now resizable and calculated from the matrix size, not from the patch size. 

Should you want to fine tune the calculations, below is the current algorithm. You can play with it in a local copy ([zip](https://github.com/d-bl/GroundForge/archive/master.zip)): adjust `docs/js/tiles.js` and test with `docs/tiles.html`
https://github.com/d-bl/GroundForge/blob/dd6945d6fc3bf9b5b433433225240a3816488390/docs/js/tiles.js#L42-L45

**Comment by Cowboynoon** [comment]
The new way to resize the panels work a charm! I can get all the design tools prototype and thread diagram on one screen easily now, and the draggable corners make resizing much easier. It feels more natural than clicking through in increments. 

Here is a screen grab of my testing it out with some notes:

I have two concerns: the drag corners of the panels are very inconspicuous, and the prototype didn't have one that I could see. An outlined triangle might do the trick.

Otherwise the screen looked very cluttered with unnecessary text and negative space taking up most of the "design space" right in the middle - to get everything on one laptop screen, the prototype pair, and thread panels make a small band at the top, and the "define" and "arrange" panels squashed at the bottom. I feel that all the 12pt texts can be removed and put in their relevant "i" info buttons or hover texts at active buttons to create space for larger visualization panels.

With the "hot corners" the "clickthrough" resize icons are not necessary any more too.


![layouttest](https://user-images.githubusercontent.com/60029271/97796669-a1da4e00-1c1d-11eb-9df3-50acfefd7f57.jpg)

**Comment by jo-pol** [comment]
The indicated texts may be clutter for seasoned users, I thought them pretty essential for the adventurous trial and error type of newbies who are too impatient for tutorials. Browsers *may* implement hover texts. So hover text should not convey essential info. Another reason not to rely on hover text: I don't know how to implement them on touch devices.

The resize corners are also depending on browser implementations, I did not find them at all on my tablet. The text field were you typed your comment also has such a drag-able corner. For those who don't see/have the hot corners, the "clickthrough" resize icons are an alternative. Having said that, I forgot to add them to the prototype diagram. So thank you for bringing them under my attention.

**Comment by jo-pol** [comment]
fixed with https://github.com/d-bl/GroundForge/pull/170
