### ISSUE TITLE
Single Coloured threads increased range

### ISSUE THREAD

**Issue by Cowboynoon** [d-bl/GroundForge#166]
a suggestion to improve functionality:

Would it be possible to increase the available colours, not with a complicated pop-up menu, but with a simple click-trough?

e.g click on the bobbin/square - red, click again - blue, click again, green, click again, yellow, click again - back to black?

and perhaps limiting the new colours to only 3 or 4 so that "mistakes" can be easily corrected

**Comment by jo-pol** [comment]
For a preview: `docs/tiles.html` in [zip](https://github.com/jo-pol/GroundForge/archive/toggle-threads.zip)

Please help to edit the [help pages](https://github.com/jo-pol/GroundForge/tree/toggle-threads/docs/help) ([procedure](https://help.github.com/articles/editing-files-in-another-user-s-repository/)) and  find colors with the best contrast, [current definitions](https://github.com/jo-pol/GroundForge/blob/57e27560ce51184624280d464cba08a27d4dd570/docs/js/tiles.js#L365-L368).

**Comment by Cowboynoon** [comment]
Here are a couple of colours that fit the current identity (logo and graphics) with a focus on purple, red, green

not saturated or pure in order to not appear black on a white background

rgb codes:

(155,2,25); //dark magenta
(181,114,209); //dark magenta
(131,75,206); //blue violet
(2,152,7); //deep green
(206,197,17); //dark yellow

![threadcolourtestblack](https://user-images.githubusercontent.com/60029271/97810667-50ae7680-1c7e-11eb-9065-91ae6f056779.jpg)
![threadcolourtestwhite](https://user-images.githubusercontent.com/60029271/97810669-52783a00-1c7e-11eb-9367-276a8a9e4581.jpg)
