### ISSUE TITLE
The target in the prototype seems difficult to hit

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#169]
The target to open an input field in the prototype diagram seems difficult to hit. Its location (highlighted in blue in the image below) is not very intuitive.

![prototype-target](https://user-images.githubusercontent.com/10553630/98481612-b9a46a00-21fb-11eb-866a-85c39e8439cf.png)

https://github.com/d-bl/GroundForge/blob/814b21bdff35cd2c914d93151ed0fa2ac6a2c42d/src/main/scala/dibl/proto/PrototypeDiagram.scala#L69-L77

**Comment by veronika** [comment]
Your blue box shows just one incoming edge.  Does the target also include the other incoming edge?

Intuitively, I expect that clicking on the circle would open the editor.   

Could you make the target a box that includes the circle and half of each edge (incoming and outgoing) around that circle (a union of bounding boxes):

![target](https://user-images.githubusercontent.com/259897/98484865-5fe27680-21e0-11eb-9a35-d53edce74756.png)

**Comment by jo-pol** [comment]
I took a bad example. The blue box is a text form field on top of the arrow. When activated the text field becomes larger and yellow. 

Actually it is easier to work without a pointing device at all. Start with a patch field. Then use the tab / shift-tab key to browse through the prototype. My iPad even has keys to browse through the form fields. Screenshot follow later.

I don't remember why I positioned the text field where I did. Might conflict with the symbol within the circle, which is select-able text on its own. That serves no purpose in our use case, but is just how the browser works in general as far as I know.

**Comment by jo-pol** [comment]
I now filled the circles to reduce the chance to click between the letter and the border. But the actual problem is more complex.
![image](https://user-images.githubusercontent.com/10553630/98590419-145ac600-22cf-11eb-94e6-6b78b63e53ae.png)

The input fields are not visible except for the active one. But they seem to be there and you can't click on/through them. It makes the first column the easiest target. 

https://github.com/d-bl/GroundForge/blob/5c7100687746c2e158be486b7d43eb2b16a69afd/docs/css/tiles.css#L30-L37

Firefox on mac shows the semitransparent field, other browsers don't. Next screenshot is with an opacity of 0.5. It seems to be the foreign object around the input field that takes the space
![image](https://user-images.githubusercontent.com/10553630/98591743-f42c0680-22d0-11eb-896f-5db8f2a7a1e3.png)
