### ISSUE TITLE
generate donwloadable Inkscape plug-in files

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#181]
drafting some ideas/requirements
- another icon to download
- calculate minimal tile size to use, or reject if not simple/brick
- see `Matrix.relativeSourceMap`
  or some GeoLinks variant of TopoLinks, see
  https://github.com/d-bl/GroundForge/blob/123d217f3c0e866f91e9ca553884501669dd8862/src/main/scala/dibl/fte/TopoLink.scala#L152-L170
  https://github.com/d-bl/GroundForge/blob/123d217f3c0e866f91e9ca553884501669dd8862/src/main/scala/dibl/fte/TopoLink.scala#L128-L137
- transform the result to the desired format

Alternative: add some filter to the download of the pair diagram (drop the markers for the color code and the invisible circles with titles for the hover texts), scaling and sheering can be don in Inkscape. Or implement the algorithm in scala and write a page for the required arguments.

**Comment by veronika** [comment]
For my personal goals, scaling and shearing are not sufficient.  In addition to the polar grid extension which already exists, I am writing other plugins that perform grid distortions based on Bezier curves as input.
