### ISSUE TITLE
Errors/Unexpected behaviour with winkie pin footside

### ISSUE THREAD

**Issue by veronika** [d-bl/GroundForge#192]
Try this [simple pattern](https://d-bl.github.io/GroundForge/tiles.html?tesselace=2x1_1&patchWidth=8&patchHeight=50&k1=ctr&c1=ct&b1=ct&a1=ctctt&k2=ct&c2=ct&b2=ctl&footside=B8,-1&tile=8,1&headside=8-,1W&footsideStitch=ctctt&tileStitch=ct&headsideStitch=ctctt&shiftColsSW=0&shiftRowsSW=2&shiftColsSE=1&shiftRowsSE=0)

The "winkie pin" footside on the right hand side in the pattern diagram shows a grey half-circle on the "8" nodes even though the number of incoming pairs equals the number of outgoing pairs.  Also, the pair diagram does not show the winkie pin correctly, the "loop" which should go around a pin has vanished and two nodes (8 and 1) have been squashed into one.

**Comment by jo-pol** [comment]
The winkie pin is missing in the ioli translator. 
Do you mean ![image](https://user-images.githubusercontent.com/10553630/123463579-fc308080-d5eb-11eb-9111-ef3f2200b3fa.png) from https://d-bl.github.io/GroundForge-help/Replace ?

The letters W-Z are not intended as stitches, just to make pairs travel a longer distance. For that reason they are semi-transparent, like repeated tiles. You might need to zig-zag a bit in certain situations for longer lines, or enlarge the whole pattern and uses longer lines everywhere by effectively using only every other grid point for a real stitch.

The same happens with the following variant of the pattern. For GroundForge a plait is a single stitch and therefore squashes stitches connected with parallel lines. Why the code considers this situation an error needs some debugging.
![image](https://user-images.githubusercontent.com/10553630/123463039-55e47b00-d5eb-11eb-985e-7420dbaae9e6.png)

**Comment by veronika** [comment]
Yes, that is what I mean by a winkie pin footside.  See also here: https://www.theedkins.co.uk/jo/lace/fowinkiet.htm

GroundForge doesn't yet support pins.  The assumption that these are just plaits is a bit too general or heavy-handed in my opinion.  When/if pins are supported, it will be necessary to view these differently.

**Comment by jo-pol** [comment]
I'm afraid that has to wait for a complete redesign. In the center part this behavior is easier to understand. After all it is GroundForge, not GuipureForge. The foot sides were an afterthought. Something that more or less accidentally worked. Perhaps this winkie pin subject needs a special entry in the side bar of the help pages.

Playing with the example from the help page I discover another problem. Only a few letters of the form field are visible for the stitches o the right. Somewhere I need a wider margin for the SVG "page" size, I guess, might be something completely different.

Workaround for now: copy-paste the content of the field temporarily somewhere else and paste the changed value back. In this case I added a pin to the winkie that does not come out too bad`tctcttprrctct`
![image](https://user-images.githubusercontent.com/10553630/123479698-9d760180-d601-11eb-983c-3b1090c123ee.png)

**Comment by jo-pol** [comment]
As mentioned this needs a complete redesign. Anything done with two pairs is a single stitch for GroundForge. W-Z are not stitches, they extend connections between stitches.

Created #195 for the unrelated issue discovered in the last comment.
