### ISSUE TITLE
initializing stitches button

### ISSUE THREAD

**Issue by MAETempels** [d-bl/GroundForge#198]
The initializing stitches button has to be pressed twice when the list of stitches in shown.

![image](https://user-images.githubusercontent.com/28353067/136189123-df303046-92f7-4355-9c28-f4b4d63d9472.png)
![image](https://user-images.githubusercontent.com/28353067/136189222-86b2029f-0fce-4abf-8794-01cbb4f5c41b.png)

**Comment by jo-pol** [comment]
the button has disappeared.
