### ISSUE TITLE
Share your patterns

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#50]
We would love to see the patterns you created with [GroundForge](http://d-bl.github.io/GroundForge). Simply add a comment with uploads and/or links.

**Comment by jo-pol** [comment]
[Pattern](https://d-bl.github.io/GroundForge/index.html?matrix=4815%0D%0A4-77&tiles=bricks&stitches=D2%3Dtctpc+A1%3Dtc+B1%3Dtc+C1%3Dtc+D1%3Dtc+A2%3Dtc+B2%3Dtc&rows=12&cols=6&left=0&up=1&pairScale=1&threadScale=0.6&transparency=0&color1=000000&color2=000000&color3=000000&color4=000000&color5=000000&color6=000000&color7=000000&color8=000000&color9=000000&color10=0D3DFF&color11=FF0000&color12=000000&color13=000000&color14=FF0000&color15=0D3DFF&color16=000000&color=CC0000), worked as freehand lace (just pins along the footsides), 8 pairs, width of the strip using DMC Perlé 5 is 17.5 mm, pin distance is 7.5 mm. An extra twist in the footside stitch quickly puts the contrasting thread back into play.

![sample](https://cloud.githubusercontent.com/assets/10553630/14233106/484c3342-f9bf-11e5-8932-af5ddb1b3b75.png)

**Comment by MAETempels** [comment]
The following matrix has a larger bricks than checkers.
.[https://d-bl.github.io/GroundForge/index.html?m=8-7-48%0A831214%0A488-7-%20148312%20%0A7-488-%20121483%3Bchecker%3B24%3B24%3B0%3B0&s1=ctct%20E4%3Dct%20F5%3Dct%20A6%3Dct%20B1%3Dct%20C2%3Dct%20D3%3Dct&s2=cross%3Dctc%20twist%3Dctc&s3=](url)

Have not found the bricks pattern yet.

The ground used is the "schuine kruisslag", afgekruist, en een rij vetergatslagen ertussen".
![image](https://user-images.githubusercontent.com/28353067/27302334-f3ac6e5e-5536-11e7-9a96-50b5039d5d61.png)

checkers		8-7-48, 831214, 488-7-, 148312, 7-488-, 121483
enlarge rows and collumns to 24 each.

**Comment by jo-pol** [comment]
[sheet](https://d-bl.github.io/GroundForge/sheet.html?patch=8-7-48%0A831214%0A488-7-%20148312%20%0A7-488-%20121483;checker) version of the pattern above. The bricks in this pattern would have to shift a third brick length at each row. The algorithm only knows how to shift half brick lengths.

**Comment by jo-pol** [comment]
Hoping you understand the ASCII-art, you might try to change triangles the following way: `|\ -> /\`.

**Comment by jo-pol** [comment]
I might be able to make the brick feature more powerfull, but don't hold your breath until it's done.

**Comment by MAETempels** [comment]
I already noticed yesterday, that a third brick length was needed.  And realised also that this particular scheme has no brick-representation. Other than the obvious (12, 34 ==> 1212, 3434). 
Which is fine with me. It was just fun to notice.

I do know ASCII, but I'm not sure what you mean with changing the triangles.

**Comment by Cowboynoon** [comment]
What an incredible tool! Thank you. I can well imagine hours and hours of experimentation and wondrous new interpretations!

My first attempt:  https://tinyurl.com/vjmof4b  

It is a variation on a classic armure beginning with a turning stitch plait and with two lock stitches in the center of each motif (ctctct)

The result is beautifully visualized, and the second and third level recursions are mesmerizing! I can't wait to try them out on the pillow!

This is the thread diagram of the initial adjustment
![screenshots - 1 (1)](https://user-images.githubusercontent.com/60029271/78020899-8c810680-7352-11ea-8cae-2ba77d2ef4eb.jpg)

This is the thread diagram, one level up.
![screenshots - 2 (1)](https://user-images.githubusercontent.com/60029271/78020913-90148d80-7352-11ea-8b00-d8ca51fa9549.jpg)

Thread diagram, third level recursion.
![screenshots - 3 (1)](https://user-images.githubusercontent.com/60029271/78020915-9145ba80-7352-11ea-8faf-1958bfc731e0.jpg)

The computer might have a hard time with the fourth level, but I can well imagine a lacemaker using this thread diagram as a pricking too!

**Comment by MAETempels** [comment]
@Cowboynoon 
Lovely variation! I am curious how the actual lace looks like.
I'm glad you like the tool.

**Comment by veronika** [comment]
Lately, I have been curious why you rarely see CC in a lace ground.  For example, this Rose ground variation seems interesting:

https://d-bl.github.io/GroundForge/tiles?patchWidth=13&patchHeight=10&a1=ccctt&b2=ccctt&a2=ccctt&a3=ccctt&b4=ccctt&a4=ccctt&tile=4-,15,7-,83,&footsideStitch=ctctt&tileStitch=ccctt&headsideStitch=ctctt&shiftColsSW=0&shiftRowsSW=4&shiftColsSE=2&shiftRowsSE=2

I will make a little sample and see whether it reveals anything.

**Comment by jo-pol** [comment]
Thanks for all who participated through this line of conversations and examples. We now have a [user group](https://groups.io/g/groundforge) that better suites sharing and helping one another. 

These issue are intended to keep track of bug reports and wish lists.
