### ISSUE TITLE
Implement diamond tiles

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#56]
The [predecessor](http://jo-pol.github.io/DiBL/grounds/index.html) of GroundForge has an implementation for diamond tiled patterns. The number of stitches are limited. 

To provide an implementation for GroundForge we need <strike>a variant of [`Matrix.brickWallToCheckerboard`](https://github.com/d-bl/GroundForge/blob/3158719c8e431e1ce1deb746d1a9556a48159045/src/main/scala/dibl/Matrix.scala#L34-L52) and [`Settings.getTitle(row,col)`](https://github.com/d-bl/GroundForge/blob/3158719c8e431e1ce1deb746d1a9556a48159045/src/main/scala/dibl/Settings.scala#L31) class</strike> to implement another subclass of [TileType](https://github.com/d-bl/GroundForge/blob/9a71325d666e18a2fce069af6421ad53e60377d7/src/main/scala/dibl/TileType.scala#L25-L27) named Diamond. <strike>The latter should return the original cell-id, not the id of the cell in the expanded/absolute matrix.</strike> When numbering cells like a spreadsheet, `Diamond.toChecker` should map a 3x3 matrix to:

|  | _A_ | _B_ | _C_ | _D_ | _E_ | _F_ |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | -- | C2 | -- | **A1** | -- | B3 |
| 2 | C3 | -- | **A2** | **--** | **B1** | -- |
| 3 | -- | **A3** | **--** | **B2** | **--** | **C1** |
| 4 | A1 | **--** | **B3** | **--** | **C2** | **--** |
| 5 | -- | B1 | **--** | **C3** | **--** | A1 |
| 6 | B2 | -- | C1 | **--** | A3 | -- |

Of course other dimensions than 3x3 should als be supported.

Note that the TileType class doesn't yet support the pattern sheets. This class prepares for hexagonal tiles too and perhaps even more.

**Comment by jo-pol** [comment]
@rvanheest

This issue leads to an interesting puzzle. In fact I need three (for now, there seem to be 17 tiling symmetries, don't know yet which ones are applicable) sub-classes of an abstract version of Settings. That is simple enough, but how do I keep the apply method DRY? It has a completely different API, the current brick-boolean originates now from a check box on the HTML page, which should become a set of radio buttons. This argument is not required for the sub-classes.

**Comment by jo-pol** [comment]
Found a solution: a map with the HTML radio-values as keys and tuples with a toChecker method and a Settings class.

**Comment by jo-pol** [comment]
In Java it would not be possible to dynamically create the desired subclass, not sure how scala handles it. An alternative would be to put the toTitle method in the map, and pass this method onto the constructor of the one and only settings class. This makes the implementation even more symmetric: one method that puts the cells of the smaller matrix at the correct positions in the larger matrix, one method that gets the labels in the larger matrix referring to its original position in the smaller matrix.

**Comment by Neon22** [comment]
sounds good - consider that eventually you might want to allow user to "attach" any suitable pattern to an 'edge' of the growing master pattern to make complex patterns from the base tilings. This approach seems like it might enable this kind of end goal.

**Comment by jo-pol** [comment]
I'm afraid I don't understand. 

So far Veronika published matrices for diamond, brick and checker board tiles. The diamonds I used for the predecessor of GroundForge, no algorithm to transform a diamond to checker but an SVG template for each dimension of matrices. 

Whatever the type of matrix/tiles so far, they are (partially) repeated to create a rectangular patch of lace. So far I refactored the code to avoid repeated if-the-else constructs. But did not yet get around to implement the algorithm for diamond tiles and convert the [tuples](https://github.com/jo-pol/DiBL/wiki/Input-Files#nodes--tuples) into [characters](https://d-bl.github.io/GroundForge/images/legend.png) for these [3x3](https://github.com/jo-pol/DiBL/blob/e6122201c2c527763b8849a66e8329f0ba2698b2/web/grounds/src/main/scala/dibl/Graphs.scala#L134-L142) and [4x4](https://github.com/jo-pol/DiBL/blob/e6122201c2c527763b8849a66e8329f0ba2698b2/web/grounds/src/main/scala/dibl/Graphs.scala#L306-L516) matrices.

**Comment by jo-pol** [comment]
Closing this issue. 

An experimental convenience form in branch [brick-variations](https://github.com/d-bl/GroundForge/tree/brick-variations) will lead to another approach, likely making the tile classes deprecated. This new approach replaces the brick/checker options with two shift parameters allowing more types of translations. To play with the new form, download or checkout the branch and try `docs/_includes/tiles-form.html` in your browser. There will only be a 'go' button at the bottom of the page for the old checker/brick patterns where the bricks are shifted by half a brick.
