### ISSUE TITLE
Custom rithm of thread colors

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#58]
Let the user specify their own rhythm of colors in a thread diagram, rather than having to paint threads one by one. For example: repeat 2 times red, 4 times blue, 2 times green.

Several design options to consider
* A simple text field such as the patterns of dots on http://jo-pol.github.io/DiBL/polar-grids it becomes automatically part of the URL when choosing submit allowing to make the chosen colors part of a bookmark. A datalist can provide some default examples. The browser may remember some user choices too. Simple to implement but not very  @WYSYWIG.
* Assemble with drag-and-drop swatches that can be dragged around like the thumbnails. The thumbnails simply swap their positions, but the color swatches should have a static pool to drag eventually multiple times into the active sequence of colors. But how to remember and share preferences in a simple way?
* ???

@neon22

**Comment by jo-pol** [comment]
Functionality should be good enough now. Just don't now how to get the top bar of the triangle semi-transparent in https://github.com/d-bl/GroundForge/blob/gh-pages/colorpicker/colorChooser.gif
That might look a little better.

**Comment by jo-pol** [comment]
Hm, broke the submit button due to some form validation on the hidden color fields.

**Comment by Neon22** [comment]
Looks very good.
Might I suggest that you loop on first noncolor square (user has not added a color).
If you do that then:
 - by default - all black like now if entire palette untouched.
 - if user enters one color - all threads that color
 - if user enters two then repeats, etc....

**Comment by Neon22** [comment]
Is this any better ?
![colorchooser2](https://cloud.githubusercontent.com/assets/899355/16170013/7889b2b4-3597-11e6-9e81-23650462f0fa.gif)

**Comment by jo-pol** [comment]
To my naked eye it looks as bright, though git sees a difference. When you save the page on your hard disk you can try for yourself.

In the mean time I fixed the submit button partially, validation worked differently on a local page than on a public page. The colors do show up in the diagram but not in the sequence of swatches.

**Comment by jo-pol** [comment]
Don't understand the remaining submit problem. When debugging the JavaScript `document.getElementById('color1').value` shows the value in the URL and diagram, but when inspecting the value with the DOM it's black.

It probably all has to do with the invisibility of the input field, but width zero doesn't work as wanted and would make the sequence too wide. It's a real pity that input [type color](http://www.w3schools.com/jsref/dom_obj_color.asp) has too little support.

**Comment by Neon22** [comment]
![colorchooser3](https://cloud.githubusercontent.com/assets/899355/16174348/dc26837c-3611-11e6-9746-6508991d5c3b.gif)

**Comment by jo-pol** [comment]
You probably missed I'm using another colorchhooser now which doesn't use a masking image. It allowed me to fix problems with initialising the form from an URL after bookmarking a pattern via submit.

I choose to terminate the sequence with white in stead of your proposal to allow for just an occasional but nevertheless repeating contrasting thread.

**Comment by jo-pol** [comment]
@Neon22 
Managed to add [your](https://github.com/d-bl/inkscape-bobbinlace/pull/25) bobbins to the animated diagrams with some thread wrapped around their necks. Just a pity the same line has to go all around the bobbin.

**Comment by Neon22** [comment]
I see what you did there :) nice. Maybe killing the stroke will help. Instead add two lines across as a new stroke-only addition. so two shapes for the bobbin. only 1 has stroke style

**Comment by jo-pol** [comment]
I understand how to do that with InkScape or SVG in general, but not [how to tell](https://github.com/d-bl/GroundForge/blob/7c6059508a6b0338bef51e2cd06fde83b492bccd/js/show-graph.js#L136) D3js in a simple  way.

**Comment by jo-pol** [comment]
With simple I mean: Each node is constructed out of a shape of one path. I referred to the wrong code lines above. Here the [correct ones](https://github.com/d-bl/GroundForge/blob/d969e392ea5063c2c3f26655ad64eb5bc1364db3/js/show-graph.js#L146-154)

It is possible to put a `<title>...</title>` inside a `<path>` but not to nest paths.  So for bobbins I would have to create a group with two paths to some of the nodes and a simple path for other nodes. It requires more knowledge of D3js than I currently have. Other issues are more important.

**Comment by Neon22** [comment]
Here's a modified bobbin (yours) which works. When setting bobin color - leave the outline as the thin black and change the fill color to match the thread color.
Can't atach svg so zip
[bobbin-2.zip](https://github.com/d-bl/GroundForge/files/334023/bobbin-2.zip)

made by grouping the svg into one shape. Probbaly also possible to make similar shape by combining two or more together...

**Comment by jo-pol** [comment]
Setting the fill in stead of the stroke is not very trivial at first sight. I'm currently using the same CSS-class for the threads and bobbins.

**Comment by Neon22** [comment]
I know this is a seelction but I think using the conditionals might work ?
```var node = container.selectAll(".node").data(args.nodes).enter().append("svg:path")
        .attr("d", function(d) { return (d.bobbin ? diagram.shape.bobbin : d.pin ? diagram.shape.pin : diagram.shape.stitch)})
        .attr("class", function(d) { return "node " + (d.startOf ? "threadStart" : d.thread ? ("thread"+d.thread) : "")})
        .style('opacity', function(d) { return d.bobbin || d.pin ? 1 : fullyTransparant})
        .style('fill', function(d) { return '#999999'})
.style('stroke', function(d) { return d.pin ? 'none' : '#000000'})
```
so something like .style('fill', function(d) { d.bobbin ? color : black })

**Comment by jo-pol** [comment]
The actual color is applied at line [177] and [185]. The variable with the color should somehow be replaced with a function returning the color, like the function diagram.path (called at line [194], defined at line [80]) returns the value for the `d` property for the `<svg:path>` of a link. I didn't say "impossible" but "not trivial". 

[177]: https://github.com/d-bl/GroundForge/blob/53acf502eaaa1a255602a68d9bd90432a6fc88ec/js/show-graph.js#L177
[185]: https://github.com/d-bl/GroundForge/blob/53acf502eaaa1a255602a68d9bd90432a6fc88ec/js/show-graph.js#L185
[194]: https://github.com/d-bl/GroundForge/blob/53acf502eaaa1a255602a68d9bd90432a6fc88ec/js/show-graph.js#L194
[80]: https://github.com/d-bl/GroundForge/blob/53acf502eaaa1a255602a68d9bd90432a6fc88ec/js/show-graph.js#L80

Furthermore I prefer to apply the color at least to the stroke so it automatically gets the same width as the threads. Otherwise you would have to change the shape of the bobbin along with the stroke-width of the thread whenever I get around to set the widths of threads too.

**Comment by jo-pol** [comment]
Bobbins now have the same fill as color. Now that I fixed it I suppose that was more or less you was trying to tell me. I just was distracted with the predefined functions that are said to perform better than inline functions, in this case only the latter can do the job in an easy way.

**Comment by Neon22** [comment]
congratulations. That looks fantastic
