### ISSUE TITLE
Shape of twists

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#70]
On the left of the image how the current [calculations] make the twists appear, on the right the desired looks.

Given the coordinates for a and d (any orientation) I need the calculations for b, c, e and f.  The starting points b and e should not lay on the straight lines between a and d, but on curves between a and d. The result should also have a constant width, so not scale with the distance between a and d, but stretch. Calculations should be fast and simple rather than exact so no bezier interpolation.

[calculations]: https://github.com/d-bl/GroundForge/blob/master/src/main/scala/dibl/SVG.scala#L139-L142

![naamloos](https://cloud.githubusercontent.com/assets/10553630/21436349/5b44b1de-c87e-11e6-9bf2-7e1132ead540.png)

**Comment by jo-pol** [comment]
The lines c-d-a-f can keep their 45° angles, but the lines c-d and a-f should get a constant length, currently its half the length of a-d. We could use the same principle for b-a-d-e, just a shorter fixed length.

**Comment by jo-pol** [comment]
Rewording the implemented situation on the left:

Point `b` and `e` are put on 1/4th of the given line `ad`, for the points `c` and `f`  the given line `ad` is rotated around its own centre.

An acceptable effect for the most common situation. But ugly in case of long distances in the foortside. Pull on a generated diagram to see the effect.

On the right the desired situation: mirrored `s` shapes with sections cut out for the over/under effect. A kind of sinus with the wave length defined by  the given line `ad` but a fixed wave height.

**Comment by jo-pol** [comment]
Forgetting the image above the problem can be narrowed down to:

Given the coordinates of A and B, a 45 degree angle between A, B and C, the length for B-C: how do I calculate the coordinates for C?

**Comment by jo-pol** [comment]
The current caculations (scala, the last expression is the implicit return value, `${...}` inserts an expression in the string `s"..."` ) 
`s` stands for the source of the link, `t` for the target 
```scala
  def pathDescription(link: LinkProps, sX: Double, sY: Double, tX: Double, tY: Double): String = {
    val dX = tX - sX
    val dY = tY - sY
    def mid = if (link.left)  s"S${sX - dY / 3 + dX / 3},${sY + dX / 3 + dY / 3}"
              else            s"S${sX + dY / 3 + dX / 3},${sY + dY / 3 - dX / 3}"
              else " "
    if (link.end == "white")
         s"M$sX,${sY + mid} ${tX - dX / 4},${tY - dY / 4}"
    else s"M${sX + dX / 4},${(sY + dY / 4) + mid} $tX,$tY"
  }
```

The desired `b`, `c`, `e` and `f` could be calculated like `mid` If we first resize the the line a-d alias source-target to some predefined length.  To calculate t' we have to solve the following two equations:
```
square(sx - tx') + square(sy - ty') = square(l)
(sx -tx)/(sy - ty) = (sx -tx)'/ (sy - ty')
```

**Comment by jo-pol** [comment]
An example in practice: ctct at step1, ctt at step 2

<img width="197" alt="twists" src="https://cloud.githubusercontent.com/assets/10553630/25629715/d1f75216-2f6a-11e7-92d1-8cf3579780af.png">

**Comment by MAETempels** [comment]
[issue 70.pdf](https://github.com/d-bl/GroundForge/files/1056230/issue.70.pdf)

**Comment by jo-pol** [comment]
Must have done something wrong with the new [calculations] as the results are asymmetrical: the distance between the source and the green curveTo does not equal the black curveTo and the target. 

Two details to address later:
* the green curveTo should connect to the source.
* move the source and target not only along the line but also sideways.

[calculations]: https://github.com/d-bl/GroundForge/blob/31b2cd16e0d484aba9dcdd210598355bdc579bc7/src/main/scala/dibl/SVG.scala#L123-L171

![twists](https://user-images.githubusercontent.com/10553630/26994448-026e0f78-4d68-11e7-9309-57c57c526dbd.png)

**Comment by jo-pol** [comment]
Another [calculation] attempt is still not right. The yellow lines _source-curveTo_ have the intended 45 degree angle with the line _source-target_, the orange lines _target-curveTo_ are stretched to about half that angle.

[calculation]: https://github.com/d-bl/GroundForge/blob/a10d3029d2be81a0185c41dadf116da8f4387976/src/main/scala/dibl/SVG.scala#L131-L173

![twists](https://user-images.githubusercontent.com/10553630/27002402-979c8ba0-4de1-11e7-8bc8-6220319434b2.png)

The red-green twist shows that the chosen approach (even if the orange lines are fixed) requires a minimum twist length of about twice the yellow/orange line length.

**Comment by jo-pol** [comment]
Must have the [rotation](https://github.com/d-bl/GroundForge/blob/a542d1e9af2680dc7c509aaee4777181924149f7/src/main/scala/dibl/SVG.scala#L168-L170) wrong.

**Comment by jo-pol** [comment]
The width of the twists is ok now. Remains moving the starting points.

![twists](https://user-images.githubusercontent.com/10553630/27049282-2834e67a-4faf-11e7-9dac-4f35baf682d8.png)
