### ISSUE TITLE
Reword step-1-2-3

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#88]
The paragraph titles step-1-2-3 may raise some eye brows. We could rename the stitches paragraph to "stitch examples" and "step one" to "choose stitches" or "select stitches". But what about step 2 or 3? The warning about overwhelming the browser should also be changed along as well as other references.

The page used to have "recursive" as address, but that might scare off the mathematical challenged. With the droste effect we could get around the expression yet still talk about it. But I don't know wether that rings a bell among the mathematical challenged.

**Comment by MAETempels** [comment]
I like "droste". 
The word "step" could be taken as "things I HAVE to do".
Perhaps "step 1" => "select stiches & the diagram" or "result"; "step 2" => "extention" or "more generations"?
So names instead of actions.

I like the "easy", "more", "advanced" paragraph. Is it clear to everyone, that the parameter-section belongs to "advanced"?

**Comment by jo-pol** [comment]
I was thinking about "step 1" => "Pair and Thread Diagrams" but I don't know yet what to do with "step 2" and "step 3". Somehow using the "droste effect" for them might raise too many eyebrows. Perhaps "Threads as Pairs" respective "Threads as Pairs - Again". Then the "droste effect" remains something for the wiki pages.

**Comment by jo-pol** [comment]
With the above proposal I still lack inspiration how to reword the linked stitches:
> The links take you down to step one with a diagonal base pattern. Show step one and two to uncover a traditional pattern.

**Comment by jo-pol** [comment]
Replacing `step` with `level` or `diagrams level` doesn't require drastic rewording, though still some. This limited rewording doesn't mean it's done in a minute as it also touches coding fragments some of which could break links by others we can't know about.

I think we need to keep the user-guide title [2-step-method](https://github.com/d-bl/GroundForge/wiki/Reversed-engineering-of-patterns#2-step-method) on the reversed engineering page.

**Comment by jo-pol** [comment]
fixed with b1a10db
