### ISSUE TITLE
Parameter-section belonging to "advanced"

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#91]
This issue arose from #88 

The indentation of the parameters form is aligned to belong to "advanced patterns" to not scare off the less daring. I don't know "everyone" understands that. Even clever people may overlook it as they tend to skip the manual. I'm considering rephrasing the text of the advanced paragraph to stress the advancedness of the parameters. Could that help?

> The user guide explains how to recognize existing patterns in the gallery or how to set the parameters to create a desired pattern.

In fact it is a bit of a mix. The "simple patterns" and "more patterns" (through the stitch examples) set the matrix and tiling parameters, so you don't have to bother about them in these cases. But resizing the pattern in terms of number of stitches, or trying another foot side has nothing to do with advanced creation of patterns. 

The box around the parameter form is the default presentation of an HTML feature intended to group fields in a form. I used it heavily before the fields were grouped into tabs (which are dropped again) as show at the bottom of #89. I could use other visual clues such as a background color rather than a box or whatever springs to your minds.

**Comment by jo-pol** [comment]
@MAETempels 
> als je op de link bij crclct klikt, en je komt weer terug

At last I think I understand your misunderstanding: Selecting a `stitches` link from a gallery pattern or one of the link from the `stitch examples` sets the matrix and tiling parameters, the latter also sets the stitches fields for step one and two. If you want to apply some stitch on a selected pattern, you have to copy-paste the `ct` sequence in the stitches field, either as default or for a specific stitch-id.

How to make all these subtle implications clear without using too many words on the page itself?

**Comment by jo-pol** [comment]
Perhaps something like

> The methods above set at least the matrix and tiling parameters. The user guide explains how to recognize existing patterns in the gallery and if not there, how to set the parameters to create a desired pattern.

**Comment by jo-pol** [comment]
I guess the "more pattern" section should also somehow hint on the base patterns to prevent the above misunderstanding.

**Comment by MAETempels** [comment]
I'm sorry, but I think that is not what I meant.
The little examples of the stitches have links underneat them. If I click one to see what's it about, and then return to the main page, my parameters are set back to default (5-;-5). Quite annoying ...
Because I have not remembered what example I chose from the gallery... :-)

**Comment by jo-pol** [comment]
Could you be more specific about what you mean with "return to" (which button do you click or link do you follow) or what you mean with the "main page".  Clicking on the linked stitches keeps you on the [main](https://d-bl.github.io/GroundForge/) page.

What your browser remembers and how to recall is explained in a [help page](https://github.com/d-bl/GroundForge/wiki/Choose-Stitches#buttons-and-browser-history), hope that helps. 

I'm afraid we are wondering off from the topic. Is that also addressed clear enough now?

**Comment by jo-pol** [comment]
The page has been reworded over and over and a lot moved to the wiki pages. The short "get started" should make it clear now.
