### ISSUE TITLE
Failing patterns

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#93]
Problem
---------

#68 and #69 fixed a lot of patterns that could not be generated at all. These issues sketch the approach to figure out a foot side for the pattern. Though most patterns are OK now, still some patterns render just a single bobbin because it fails. On the gallery page the following patterns fail with 9 columns:

> "-5-5 5-5- -5-- B-C-;bricks", "5831 -4-7 5--- -C-B;bricks", "B-5-C- -5-5-- B---C-;bricks", "B-B- -B-B C-C- -C-C;bricks", "6868 -4-4 5--- -C-B;bricks", "586- -4-5 5--- -C-B;bricks"

Workaround
-------------

* Try a link like https://d-bl.github.io/GroundForge/sheet.html?patch=-5-5;5-5-;-5--;B-C-;bricks
* If the rendered pattern is OK (only `x` an `+`, no `T` nor `*` nor any other number of lines at one point) you hit a bug in the generator
* Try to vary the shift parameters and number of columns. You may have to increment up to twice the matrix width or height. That might take a lot of attempts.

Request
--------

The more examples of failing patterns we can collect, the better the chances we can analyze the problem. Interesting details are with which values for shift-left, shift-up and number of columns does a faulty pattern succeed?

cc @MAETempels

**Comment by jo-pol** [comment]
The following patterns work for all number of columns if shift-up = 1

> "-5-5 5-5- -5-- B-C-;bricks", "5831 -4-7 5--- -C-B;bricks", "B-5-C- -5-5-- B---C-;bricks", "6868 -4-4 5--- -C-B;bricks", "586- -4-5 5--- -C-B;bricks"

But `B-B- -B-B C-C- -C-C;bricks` needs further attempts.

**Comment by jo-pol** [comment]
None worked for `B-B- -B-B C-C- -C-C;bricks` when tried with 

```scala
for{
      shiftLeft <- 0 until 16
      shiftUp <- 0 until 16
      cols <- 8 until 32
    }
```

So this one delivers just another variant for pin positions

**Comment by jo-pol** [comment]
Note on 86c4e40 needing a fix by bb5cf63 :
Shifting a brick pattern up manually means not only that the first row of the matrix becomes the last, but also both halves of the moved rows need to swap, so

    abcd
    efgh
    ijkl

becomes 

    efgh
    ijkl
    cdab

**Comment by jo-pol** [comment]
Unzip attached SVG and show it in your browser. Follow each link and show the first set of diagrams. Some render a single bobbin (indicating an error) with the default parameter value of 5 columns. The others will render with 5 columns, but not for another number of columns. They will succeed when setting the shift-left parameter to one, two or three.

We have to investigate the common factor why the algorithm fails that is illustrated with images in #68 and #69 The first step of this investigation: where does the algorithm cut through the repeated matrix? 
[GallerySpec.svg.zip](https://github.com/d-bl/GroundForge/files/1031376/GallerySpec.svg.zip)

**Comment by jo-pol** [comment]
The image shows a pattern that only works for 3, 4 or 5 columns (and 30 rows). To get the second image the animation is intercepted with the debugger of the browser [at the start]. The third image shows the final stage of the animation. The last figure is the thread diagram with 3 columns and 21 rows. 

[at the start]: https://github.com/d-bl/GroundForge/blob/5a91387/docs/js/show-graph.js#L26

![failing](https://cloud.githubusercontent.com/assets/10553630/26498977/3610af26-4231-11e7-8da3-64e670f0759c.png)


Comparing the intercepted start with first figure (the last from the zip in the previous comment) shows the cut-out of the matrix. Nine columns cause the same "corner-pins", so that doesn't seem to be the clue for the problem. The cyclic effect of the pair diagram is caused by the second last pair not being used. Hovering over the diamond starts of the threads, we can also see a pair number is skipped. With three columns the pattern fails at 7, 15 and 23 columns. Now I remember the algorithm for #68 and #69 (to close the footside) works bottom up, so it might be the bottom corners or gaps are also significant.

A sidestep for #96: the different colors for different stitches can help to show some ID's without tool tip.

    ct A1=ctt C3=ctct D2=ctc

**Comment by jo-pol** [comment]
Another weird thing with the [pattern] of the previous message: The thread diagram draws the twists on the right, while the pair diagram draws the twist mark on the left. Other patterns don't suffer from this phenomenon, such as [ctctc] at the second diagram level.

[pattern]: https://d-bl.github.io/GroundForge/index.html?m=5-;bricks;7;5;0;0&s1=ctctc&s2=ctc,B14=ctcll,B15=ctcrr,B16=ctctt&s3=&#diagrams
[ctctc]: https://d-bl.github.io/GroundForge/index.html?m=5-;bricks;7;5;0;0&s1=ctctc&s2=ctc,B14=ctcll,B15=ctcrr,B16=ctctt&s3=&#diagrams

cc @MAETempels

**Comment by MAETempels** [comment]
I wonder why you use 7, 15, 23 columns. As the matrix is 4x4, so I expect 8 or 16 ...
The matrix works with 16 columns and rows (an a shift up and left). 8 columns and 16 rows also works.
It is a nice pattern!

[https://d-bl.github.io/GroundForge/index.html?m=6-58%0A-5-4%0A--5-%0A-B-C%3Bbricks%3B16%3B16%3B1%3B1&s1=ct%20A1%3Dct&s2=cross%3Dctc%20twist%3Dctc&s3=](url)

**Comment by MAETempels** [comment]
The use of a relative small number of collumns gives an other opportunity: BraidForge (bandjes).
I imagine to have a matrix that repeats only verticaly. The sides are taken care of in the matrix itself.

I can very well imagine that when using less than twice the with of the matrix for the number of collumns, e.g. 5 or 7, the resulting pair-diagramms will be different or fail when shifted to the left.

**Comment by jo-pol** [comment]
Won't fix as we have plans for custom footsides: https://github.com/d-bl/GroundForge/issues/111#issuecomment-354661495
