### ISSUE TITLE
fix numbering of stitches

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#96]
It is not possible to choose something different for [every other stitch](https://d-bl.github.io/GroundForge/?m=88%0A11%0A88%0A11%3Bbricks%3B6%3B6%3B0%3B0&s1=ct%20A1%3Dctct&s2=cross%3Dctc%20twist%3Dctc&s3=)

Though it breaks the content for existing links, fix the problem with the [mistaken ID's](https://github.com/d-bl/GroundForge/wiki/Reversed-engineering-of-patterns#2-step-method).

**Comment by jo-pol** [comment]
A wiki page explains users how to [fix](https://github.com/d-bl/GroundForge/wiki/Fix-Old-Links) the changed content of  link.

**Comment by MAETempels** [comment]
Looking at the matrix for the pagode-ground, the ID's are mistaken. When following this ID's in a picture of the ground  that shows what went where, I noticed, the ID's are from a shifted matrix. Shift left 2. Filling in this matrix gets the ID's back on the original position (so also shifted left 2).
4312; 6-78 gives the ID's of 1243; 786- and v.v.
(The checkers matrix is even more distorted.)

**Comment by jo-pol** [comment]
Let us first establish the requirements. 

* Each tile of the matrix should get the same ID's in the pattern. An offset is not relevant as long as each row and column gets the same offset.
* It should be possible to play with the footside, without having to redefine the stitch specifications.

For example a brick matrix of 3 rows and 4 columns should repeat horizontally and vertically:

    abcdabcd
    efghefgh
    ijklijkl
    cdabcdab
    ghefghef
    klijklij

shifted left once should result in

    dabcdabc
    hefghefg
    lijklijk
    bcdabcda
    fghefghe
    jklijkli

**Comment by MAETempels** [comment]
ID's as such do not have meaning. They can be quite random. However, the userguide suggest there is a connection between the matrix and the ID's. 

It looks, as if **all** bricks matrices get a shift  size "**half brick**" to the left with the ID's.  (One test with a checkers matrix reveals the same shift.)
As indeed is explained in the userguide.  

So, if it is a consequent shift, does it need fixing? As long as  I understand how it works, I'm fine with the "bug". I only noticed, when trying to figure out what went where in the pagoda ground versus the matrix.

Some simple test:

matrix -5, bricks
Expected is ID B1, however, the picture shows A1.
matrix 5-, bricks
Expected is ID A1, however, the picture shows B1.

matrix -5-5, 5-5-, bricks
seems correct at first glance, however, the most left ID first row is spaces, and then D1. I would have expected a B1. Suggesting a shift 2 to the left.

matrix 5831, -4-7, bricks
at first glance, looks oké, however, looking closely at the matrix and the pair-diagram also reveals a shift 2 to the left.

matrix 1483, 8-48, bricks
Idem. Where A1 is expected, C1 shows up. Etc.

I have not figured how this works in checkers.
One test
matrix 4831 -488 3148 88-4, checkers
Where A1 is expected, C1 shows up. Etc. Also shifted left 2.

**Comment by MAETempels** [comment]
Testing a bigger matrix:
1488-483, 8-483148, 831488-4, 488-4831 bricks, 8 collummns.
this gives a shift of 4 collumns. Where A1 is expected, E1 shows up.

**Comment by jo-pol** [comment]
I opened the issue because I thought it wasn't possible to create Lidwien Roording's "om en om", which translates as "every other". I tried it with `88,11;bricks` and jumped to conclusions, but it works for [`88,11;cheker`](https://d-bl.github.io/GroundForge/index.html?m=88%0A11%3Bchecker%3B5%3B5%3B0%3B0&s1=ct%20A1%3Dctct%20B2%3Dctct&s2=cross%3Dctc%20twist%3Dctc&s3=). 

As I guess the first [requirement](https://github.com/d-bl/GroundForge/issues/96?_pjax=%23js-repo-pjax-container#issuecomment-304086287) doesn't seem to be a problem. But take a look at [this example](https://d-bl.github.io/GroundForge/index.html?m=5831%20-4-7%3Bchecker%3B9%3B9%3B0%3B0&s1=ct%20C1%3Dctct&s2=cross%3Dctc%20twist%3Dctc&s3=), then increment the shift-left parameter and see how the diagrams change. The second requirement should prevent that change and allow playing with the footside.

**Comment by MAETempels** [comment]
8888,1111;bricks works for "om&om". 

88,11;bricks gives ID's in the columns that will not do for "om&om".
**A1** B1 A1 
A2 B2 A2
B1 **A1** B1

[https://d-bl.github.io/GroundForge/index.html?m=8888%0A1111%3Bbricks%3B16%3B16%3B0%3B0&s1=ctct%20A1%3Dct%20C1%3Dct%20B2%3Dct%20B4%3Dct%20D2%3Dct&s2=cross%3Dctc%20twist%3Dctc&s3=](url)

**Comment by MAETempels** [comment]
Look at "this example". 
When changing the number of rows and columns to 16, shifting left 1 has no effect.

**Comment by jo-pol** [comment]
The topic of this discussion is confusing. The first message states "_It is not possible to choose something different for every other stitch_". That claim is not true as shown [here](https://d-bl.github.io/GroundForge/index.html?m=88%0D11;bricks;5;5;0;0&s3=&s2=cross=ctct,twist=ct&s1=A1=ctct%20B1=ct%20A2=ct%20B2=ctct)

So I'm closing this issue and started a new one: #108
