### ISSUE TITLE
resize buttons of diagrams execute multiple steps when touching once

### ISSUE THREAD

**Issue by MAETempels** [d-bl/GroundForge#98]
The following are some things I noticed. Just personal inconveniences.

- It would be nice, if the items in the gallery have visual "numbers". Maybe with a suffix for different pinpoints. This will be usefull for referencing, remembering which one is used and teaching.

- When resizing the thead diagrams with [-], the colours faint.

- Resizing sometimes takes several steps at one time. Maybe its just me pushing to hard or something.

- The "download" and "full screen" options use the resize that is done ([+] and [-]).
How do I get all threaddiagrams  I'm viewing the same "size" ?

**Comment by jo-pol** [comment]
* The gallery is not stable, the order might change and multiple images might merge. For example the three Torchon images should be reduced to a single one, there used to be a technical limit in the number of variants for a single link. Right click a gallery image and the browser can show it stand-alone, for example https://d-bl.github.io/GroundForge/thumbs/138.png. You can find the full list at https://github.com/d-bl/GroundForge/tree/master/docs/thumbs or by saving the gallery page locally. Their numbers might be stable but you will notice a lot of gaps. You can create your own index like for example the Whiting-Index in the wiki pages, either reusing the gallery images or your own screen shot snippets.
* The width of the lines decreases with the zoom factor making them faint. Increasing the width could close the gaps for the over/under effect.
* Don't understand what you mean.
* For now I have no better suggestion than press the show button again and count how many times your applied the [+] and/or [-]. Using the scroll wheel to zoom would be less accurate.

**Comment by MAETempels** [comment]
- (I did not try to make bullets :-)   )

-  When using numbers for identification, there may be gaps, and there does not have to be any order 
whatsoever.  :-)

- nr 3) I meant: I press [+]  or [-] once, and the images resize several steps at once. As far as the smallest or biggest. Maybe I do something wrong. I use a pad instead of a mouse.

**Comment by jo-pol** [comment]
Tried the touch-pad on a mac without trouble. So I might need a hands-on experience on your hard ware some day.

**Comment by jo-pol** [comment]
Possible workaround: wait until the animation is complete. The last adjustments however may be hardly visible.

**Comment by jo-pol** [comment]
obsolete, the complete page has been replaced
